// <auto-generated />
using System;
using MAQ_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAQ_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MAQ_API.Models.TempahanRamadan", b =>
                {
                    b.Property<int>("TempahanRamadanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TempahanRamadanId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("BookedDate")
                        .HasColumnType("date");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ICNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TempahanRamadanId");

                    b.HasIndex("BookedDate");

                    b.HasIndex("ICNumber", "BookedDate")
                        .IsUnique();

                    b.ToTable("TempahanRamadans");

                    b.HasData(
                        new
                        {
                            TempahanRamadanId = 1,
                            Address = "No 1, Jalan Contoh, 50000 Kuala Lumpur",
                            Age = 36,
                            Amount = 350.00m,
                            BookedDate = new DateOnly(2027, 2, 20),
                            ContactNumber = "0123456789",
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ahmad bin Ali",
                            ICNumber = "900101-10-1234"
                        },
                        new
                        {
                            TempahanRamadanId = 2,
                            Address = "No 2, Jalan Contoh, 40000 Shah Alam",
                            Age = 41,
                            Amount = 500.00m,
                            BookedDate = new DateOnly(2027, 2, 21),
                            ContactNumber = "0198765432",
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Siti binti Hassan",
                            ICNumber = "850505-14-5678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
